substitutions:
  device_name: dormitorio_luz_ventilador
  enable_bluetooth: "false"
  detatched_mode: "false"

packages:
  - !include 
    file: ../sonoff-mini-r4/defaults.yaml
    vars: 
      device_name: ${device_name}
      enable_bluetooth: ${enable_bluetooth}

sensor: !include 
  file: ../sonoff-mini-r4/sensors.yaml
  vars: 
    device_name: ${device_name}

text_sensor:
  - platform: wifi_info
    ssid:
      name: "Connected SSID"
    ip_address:
      name: "IP Address"

## Physical switch to control the relay and the relay LED

switch:
  - platform: gpio
    name: Mini R4 Rele
    pin:
      number: GPIO26
      inverted: false
    id: relay
    on_turn_on:
      - light.turn_on: relay_led
    on_turn_off:
      - light.turn_off: relay_led

output:
  !include 
    file: ../sonoff-mini-r4/relay-led.yaml

light:
  - platform: binary
    name: "Relay LED"
    id: relay_led
    internal: true    
    output: relay1_led_gpio

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: false
    name: Mini R4 Switch
    on_state:
      - switch.toggle: relay
#    on_state:
#      if:
#        condition:
#          not:
#            api.connected:
#        then:
#          - switch.toggle: relay

  - platform: gpio
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: false
    name: Mini R4 Boton
    on_press:
      - switch.toggle: relay