substitutions:
  device_name: dormitorio_luz_ventilador

esphome:
  name: ${device_name}
  comment: "Sonoff MiniR4 Extreme"

esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: arduino

# Enable logging over serial/network
logger:

# Enable Home Assistant API & Node-RED Native Integration
api:

# Enable Over-The-Air updates
ota:
  - platform: esphome

wifi: 
  networks: !include { file: ../wifi-networks.yaml }

  # Fallback captive portal AP
  ap:
    ssid: ${device_name}
    password: ""

captive_portal:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "${device_name} Wifi RSSI"
    update_interval: 90s
    entity_category: "diagnostic"

  - platform: uptime
    name: "${device_name} Uptime"
    update_interval: 300s
    entity_category: "diagnostic"

text_sensor:
  - platform: wifi_info
    ssid:
      name: "Connected SSID"
    ip_address:
      name: "IP Address"

## Uncomment the following lines to enable Bluetooth scanning for BLE devices

#esp32_ble_tracker:
#  scan_parameters:
#    interval: 1100ms
#    window: 1100ms

#bluetooth_proxy:

## Physical switch to control the relay and the relay LED

switch:
  - platform: gpio
    name: Mini R4 Rele
    pin:
      number: GPIO26
      inverted: false
    id: relay
    on_turn_on:
      - light.turn_on: relay_led
    on_turn_off:
      - light.turn_off: relay_led

output:
  - platform: gpio
    pin: GPIO19
    inverted: True
    id: relay1_led_gpio

light:
  - platform: binary
    name: "Relay LED"
    id: relay_led
    internal: true    
    output: relay1_led_gpio

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      mode: INPUT_PULLUP
      inverted: false
    name: Mini R4 Switch
    on_state:
      - switch.toggle: relay
#    on_state:
#      if:
#        condition:
#          not:
#            api.connected:
#        then:
#          - switch.toggle: relay

  - platform: gpio
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: false
    name: Mini R4 Boton
    on_press:
      - switch.toggle: relay