- platform: wifi_signal
  name: "${device_name} Wifi RSSI"
  update_interval: 90s
  entity_category: "diagnostic"

- platform: uptime
  name: "${device_name} Uptime"
  update_interval: 300s
  entity_category: "diagnostic"

# Internal ESP32 CPU Die Temperature
- platform: internal_temperature
  name: "${device_name} CPU Temp"
  update_interval: 60s
  entity_category: "diagnostic"